// Mocks generated by Mockito 5.0.7 from annotations
// in eventlog/test/Domain/ProcessesController_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:eventlog/Data/datasources/ISql_Database.dart' as _i2;
import 'package:eventlog/Data/Models/Event.dart' as _i5;
import 'package:eventlog/Data/Models/Proces.dart' as _i6;
import 'package:eventlog/Data/repos/DatabaseHandler.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeISqlDatabase extends _i1.Fake implements _i2.ISqlDatabase {}

/// A class which mocks [DatabaseHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHandler extends _i1.Mock implements _i3.DatabaseHandler {
  MockDatabaseHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ISqlDatabase get database =>
      (super.noSuchMethod(Invocation.getter(#database),
          returnValue: _FakeISqlDatabase()) as _i2.ISqlDatabase);
  @override
  set database(_i2.ISqlDatabase? _database) =>
      super.noSuchMethod(Invocation.setter(#database, _database),
          returnValueForMissingStub: null);
  @override
  _i4.Future<List<_i5.Event>> readAllEvents(int? proces_id) =>
      (super.noSuchMethod(Invocation.method(#readAllEvents, [proces_id]),
              returnValue: Future<List<_i5.Event>>.value(<_i5.Event>[]))
          as _i4.Future<List<_i5.Event>>);
  @override
  _i4.Future<List<_i6.Proces>> readProcesses(int? cpr) =>
      (super.noSuchMethod(Invocation.method(#readProcesses, [cpr]),
              returnValue: Future<List<_i6.Proces>>.value(<_i6.Proces>[]))
          as _i4.Future<List<_i6.Proces>>);
}
