// Mocks generated by Mockito 5.0.7 from annotations
// in eventlog/test/Data/Db/DatabaseHandler_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:eventlog/Data/datasources/sql_Db.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite_common/sqlite_api.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeDatabase extends _i1.Fake implements _i2.Database {}

/// A class which mocks [SqlDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqlDb extends _i1.Mock implements _i3.SqlDb {
  MockSqlDb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get database => (super.noSuchMethod(Invocation.getter(#database),
      returnValue: _FakeDatabase()) as _i2.Database);
  @override
  set database(_i2.Database? _database) =>
      super.noSuchMethod(Invocation.setter(#database, _database),
          returnValueForMissingStub: null);
  @override
  _i4.Future<List<Map<String, Object?>>> readAllEvents(int? proces_id) =>
      (super.noSuchMethod(Invocation.method(#readAllEvents, [proces_id]),
              returnValue: Future<List<Map<String, Object?>>>.value(
                  <Map<String, Object?>>[]))
          as _i4.Future<List<Map<String, Object?>>>);
  @override
  _i4.Future<List<Map<String, Object?>>> readProcesses(int? cpr) =>
      (super.noSuchMethod(Invocation.method(#readProcesses, [cpr]),
              returnValue: Future<List<Map<String, Object?>>>.value(
                  <Map<String, Object?>>[]))
          as _i4.Future<List<Map<String, Object?>>>);
  @override
  void deleteTable() => super.noSuchMethod(Invocation.method(#deleteTable, []),
      returnValueForMissingStub: null);
  @override
  void createTables() =>
      super.noSuchMethod(Invocation.method(#createTables, []),
          returnValueForMissingStub: null);
  @override
  void fillTable() => super.noSuchMethod(Invocation.method(#fillTable, []),
      returnValueForMissingStub: null);
}
